color1=set(["Green","Red","Blue"])
color2=set(["Red","Yellow",'Pink'])
print("List of colors:")
print(color1)
print(color2)
print("The list of colors in list1 and not contained in list2")
print(color1.difference(color2))